import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and uses a triple-slash reference by design
    ignores: [".next/**", ".open-next/**", "node_modules/**", "db/migrations/**", "next-env.d.ts"],
  },
];

export default config;
