import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const config = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // next-env.d.ts is generated by Next and uses a triple-slash reference by design
    ignores: [".next/**", ".open-next/**", "node_modules/**", "db/migrations/**", "next-env.d.ts"],
  },
];

export default config;
